### ISSUE TITLE
error on compiling unoficial device

### ISSUE THREAD

**Issue by Kirinline206** [RevengeOS/android_manifest#21]
/prebuilts/tools-lineage/common/perl-base /home/build/android/prebuilts/build-tools/linux-x86/bin/make  -j8 CFLAGS_
MODULE=\"-fno-pic\" HOSTCFLAGS=\"-I/usr/include -I/usr/include/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -L/usr/
lib64\" HOSTCC=/home/build/android/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-gcc HOS
TCXX=/home/build/android/prebuilts/gcc/linux-x86/host/x86_64-linux-glibc2.17-4.8/bin/x86_64-linux-g++ -C kernel/mot
orola/sanders O=/home/build/android/out/target/product/sanders/obj/KERNEL_OBJ ARCH=arm64 CROSS_COMPILE=\"/home/buil
d/android/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin/aarch64-linux-android-\" CROSS_COMPILE_ARM3
2=\"/home/build/android/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin/arm-linux-androideabi-\" CLANG_TR
IPLE=aarch64-linux-gnu- CC=\"/usr/bin/ccache clang\"  modules;          fi )"
make: Entering directory '/home/build/android/kernel/motorola/sanders'
make[1]: Entering directory '/home/build/android/out/target/product/sanders/obj/KERNEL_OBJ'
ccache: error: Could not find compiler "clang" in PATH
  CHK     include/config/kernel.release
  GEN     ./Makefile
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  Using /home/build/android/kernel/motorola/sanders as source for kernel
  CC      scripts/mod/empty.o
ccache: error: Could not find compiler "clang" in PATH
make[3]: *** [/home/build/android/kernel/motorola/sanders/scripts/Makefile.build:266: scripts/mod/empty.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC      scripts/mod/devicetable-offsets.s
ccache: error: Could not find compiler "clang" in PATH
make[3]: *** [/home/build/android/kernel/motorola/sanders/scripts/Makefile.build:153: scripts/mod/devicetable-offse
ts.s] Error 1
make[2]: *** [/home/build/android/kernel/motorola/sanders/scripts/Makefile.build:410: scripts/mod] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [/home/build/android/kernel/motorola/sanders/Makefile:556: scripts] Error 2
make[1]: Leaving directory '/home/build/android/out/target/product/sanders/obj/KERNEL_OBJ'
make: *** [Makefile:150: sub-make] Error 2
make: Leaving directory '/home/build/android/kernel/motorola/sanders'
19:32:52 ninja failed with: exit status 1
#### failed to build some targets (02:32 (mm:ss)) ####
root@27016b96541c:/home/build/android#

**Comment by SonalSingh18** [comment]
ccache: error: Could not find compiler "clang" in PATH

**Comment by Mikdadali** [comment]
how to fix @SonalSingh18 sir

**Comment by hycon-os** [comment]
@Mikdadali

**Comment by Takeshiro04** [comment]
@Mikdadali what in the actual fuck

**Comment by vansh123456** [comment]
@Takeshiro04

**Comment by Lucchetto** [comment]
Sup guys

**Comment by Giovix92** [comment]
@Lucchetto aye

**Comment by pratyakshm** [comment]
@Giovix92 lol

**Comment by Introdructor** [comment]
Hi guys

**Comment by pratyakshm** [comment]
ohk

**Comment by vansh123456** [comment]
@pratyakshm Hai bhailog

**Comment by pratyakshm** [comment]
hai

**Comment by NextWork123** [comment]
Hello boys who want some pizza?

**Comment by pratyakshm** [comment]
moi want PIZZAS sand pizza and pasta
will share with @Lucchetto

**Comment by Introdructor** [comment]
Gib clang , not pizza 😂😂

**Comment by pratyakshm** [comment]
very F

**Comment by NextWork123** [comment]
best compiler ever is the pizza

**Comment by Lucchetto** [comment]
> moi want PIZZAS sand pizza and pasta
> will share with @Lucchetto

Best

**Comment by vansh123456** [comment]
@Introdructor Real Debs chat in comments huh

**Comment by Introdructor** [comment]
@vansh123456 😂😂😂

**Comment by pratyakshm** [comment]
> > moi want PIZZAS sand pizza and pasta
> > will share with @Lucchetto
> 
> Best

yos

**Comment by Introdructor** [comment]
> > > moi want PIZZAS sand pizza and pasta
> > > will share with @Lucchetto
> > 
> > 
> > Best
> 
> yos

Retards incoming 😂😂

**Comment by pratyakshm** [comment]
> > > > moi want PIZZAS sand pizza and pasta
> > > > will share with @Lucchetto
> > > 
> > > 
> > > Best
> > 
> > 
> > yos
> 
> Retards incoming 😂😂

github retards?

**Comment by Introdructor** [comment]
> > > > > moi want PIZZAS sand pizza and pasta
> > > > > will share with @Lucchetto
> > > > 
> > > > 
> > > > Best
> > > 
> > > 
> > > yos
> > 
> > 
> > Retards incoming joyjoy
> 
> github retards?

Yus 😂

**Comment by arthdoshi33** [comment]
0.o

**Comment by hycon-os** [comment]
@arthdoshi33

**Comment by arthdoshi33** [comment]
@hycon-os

**Comment by NitroFuN** [comment]
> Hello boys who want some pizza?

Wanna some pierogi?

**Comment by NextWork123** [comment]
@pizza

**Comment by Introdructor** [comment]
> > Hello boys who want some pizza?
> 
> Wanna some pierogi?

😂😂😂

**Comment by NextWork123** [comment]
me want only pizza ;-;

**Comment by gaganmalvi** [comment]
o.O

**Comment by ejbtrd** [comment]
> > Hello boys who want some pizza?
> 
> Wanna some pierogi?

bigos

**Comment by pratyakshm** [comment]
![hqdefault jpg](https://user-images.githubusercontent.com/54220235/105339933-3f349500-5c03-11eb-8df2-27e7a0b8dacd.png)

**Comment by gaganmalvi** [comment]
fratty bratty

**Comment by pratyakshm** [comment]
> fratty bratty

yoo

**Comment by vitor00almei** [comment]
Looks good

**Comment by gaganmalvi** [comment]
ayy vitor

**Comment by vitor00almei** [comment]
Sup gagan

**Comment by NextWork123** [comment]
we are doing party on this issue where is the vodka?

**Comment by gaganmalvi** [comment]
bored af, wen booting daisy?

**Comment by Manish4586** [comment]
Nais bag. Fix develops 😞😂

**Comment by gaganmalvi** [comment]
> we are doing party on this issue where is the vodka?

senddddd ahahahahaha

**Comment by pratyakshm** [comment]
ofucj.jpg

**Comment by vitor00almei** [comment]
> bored af, wen booting daisy?

When i get life

**Comment by NitroFuN** [comment]
> > > Hello boys who want some pizza?
> > 
> > 
> > Wanna some pierogi?
> 
> bigos

Good idea

**Comment by NextWork123** [comment]
i will send you very soon @gaganmalvi xd

**Comment by gaganmalvi** [comment]
> > bored af, wen booting daisy?
> 
> When i get life

i feel you man :")

**Comment by gaganmalvi** [comment]
> i will send you very soon @gaganmalvi xd

yeet lmao send send

**Comment by Peppe289** [comment]
who wants to get drunk?

**Comment by pratyakshm** [comment]
okay conversation will be cleaned up and locked in a few mins

**Comment by CloudedQuartz** [comment]
Ayy wassup

**Comment by starlight5234** [comment]
https://user-images.githubusercontent.com/62152900/105340331-bf5afa80-5c03-11eb-9b65-a17678abcf0b.mp4

**Comment by Panchajanya1999** [comment]
GCC best guys.

**Comment by gaganmalvi** [comment]
> GCC best guys.

@mvaisakh's Eva GCC wen

**Comment by Aftab-111** [comment]
I feel left out in pizza 🍕 party 🥲

**Comment by gaganmalvi** [comment]
> okay conversation will be cleaned up and locked in a few mins

gay

**Comment by gaganmalvi** [comment]
>  failsmerty1549.mp4

naacho bc

**Comment by pratyakshm** [comment]
> > okay conversation will be cleaned up and locked in a few mins
> 
> gay

be quiet, object

**Comment by gaganmalvi** [comment]
> > > okay conversation will be cleaned up and locked in a few mins
> > 
> > 
> > gay
> 
> be quiet, object

stop it brat

**Comment by pratyakshm** [comment]
> > > > okay conversation will be cleaned up and locked in a few mins
> > > 
> > > 
> > > gay
> > 
> > 
> > be quiet, object
> 
> stop it brat

bitch tf

**Comment by starlight5234** [comment]
> > > > okay conversation will be cleaned up and locked in a few mins
> > > 
> > > 
> > > gay
> > 
> > 
> > be quiet, object
> 
> stop it brat

bratty sis

**Comment by pratyakshm** [comment]
> > > > > okay conversation will be cleaned up and locked in a few mins
> > > > 
> > > > 
> > > > gay
> > > 
> > > 
> > > be quiet, object
> > 
> > 
> > stop it brat
> 
> bratty sis

**bratty daddy**

**Comment by Giovix92** [comment]
> > > > > > okay conversation will be cleaned up and locked in a few mins
> > > > > 
> > > > > 
> > > > > gay
> > > > 
> > > > 
> > > > be quiet, object
> > > 
> > > 
> > > stop it brat
> > 
> > 
> > bratty sis
> 
> **bratty daddy**

bc tf

**Comment by starlight5234** [comment]
> > > > > > okay conversation will be cleaned up and locked in a few mins
> > > > > 
> > > > > 
> > > > > gay
> > > > 
> > > > 
> > > > be quiet, object
> > > 
> > > 
> > > stop it brat
> > 
> > 
> > bratty sis
> 
> **bratty daddy**

pratty daddy

**Comment by pratyakshm** [comment]
> > > > > > > okay conversation will be cleaned up and locked in a few mins
> > > > > > 
> > > > > > 
> > > > > > gay
> > > > > 
> > > > > 
> > > > > be quiet, object
> > > > 
> > > > 
> > > > stop it brat
> > > 
> > > 
> > > bratty sis
> > 
> > 
> > **bratty daddy**
> 
> bc tf

hai favChut TM

**Comment by Giovix92** [comment]
> > > > > > > > okay conversation will be cleaned up and locked in a few mins
> > > > > > > 
> > > > > > > 
> > > > > > > gay
> > > > > > 
> > > > > > 
> > > > > > be quiet, object
> > > > > 
> > > > > 
> > > > > stop it brat
> > > > 
> > > > 
> > > > bratty sis
> > > 
> > > 
> > > **bratty daddy**
> > 
> > 
> > bc tf
> 
> hai favChut TM

hlo favchut
