### ISSUE TITLE
Failed to build when using prebuilt kernel

### ISSUE THREAD

**Issue by XayahSuSuSu** [RevengeOS/android_manifest#29]
[  0% 234/24451] //vendor/revengeos/build/soong:generated_kernel_includes genera
FAILED: /home/xayah/RevengeOS/out/soong/.intermediates/vendor/revengeos/build/so
ong/generated_kernel_includes/gen/.dummy_dep
/home/xayah/RevengeOS/out/soong/host/linux-x86/bin/sbox --sandbox-path /home/xay
ah/RevengeOS/out/soong/.temp --output-root /home/xayah/RevengeOS/out/soong/.inte
rmediates/vendor/revengeos/build/soong/generated_kernel_includes/gen --copy-all-
output -c 'PATH=/home/xayah/RevengeOS/prebuilts/jdk/jdk11/linux-x86/bin:/home/xa
yah/RevengeOS/prebuilts/jdk/jdk11/linux-x86/bin:/home/xayah/RevengeOS/out/soong/
host/linux-x86/bin:/home/xayah/RevengeOS/out/host/linux-x86/bin:/home/xayah/Reve
ngeOS/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:/home/xayah/
RevengeOS/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:/home/xayah/
RevengeOS/development/scripts:/home/xayah/RevengeOS/prebuilts/devtools/tools:/ho
me/xayah/RevengeOS/external/selinux/prebuilts/bin:/home/xayah/RevengeOS/prebuilt
s/misc/linux-x86/dtc:/home/xayah/RevengeOS/prebuilts/misc/linux-x86/libufdt:/hom
e/xayah/RevengeOS/prebuilts/clang/host/linux-x86/llvm-binutils-stable:/home/xaya
h/RevengeOS/prebuilts/android-emulator/linux-x86_64:/home/xayah/RevengeOS/prebui
lts/asuite/acloud/linux-x86:/home/xayah/RevengeOS/prebuilts/asuite/aidegen/linux
-x86:/home/xayah/RevengeOS/prebuilts/asuite/atest/linux-x86:/home/xayah/.local/b
in:/home/xayah/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
/usr/games:/usr/local/games:/snap/bin make -j12 CFLAGS_MODULE="-fno-pic" -C  O=_
_SBOX_OUT_DIR__ ARCH=arm64 CROSS_COMPILE=" aarch64-linux-android-" CROSS_COMPILE
_ARM32="arm-linux-androideabi-"   headers_install' && touch /home/xayah/RevengeO
S/out/soong/.intermediates/vendor/revengeos/build/soong/generated_kernel_include
s/gen/.dummy_dep
make: *** O=/home/xayah/RevengeOS/out/soong/.temp/sbox334692632: No such file or directory. Stop.
sbox command (PATH=/home/xayah/RevengeOS/prebuilts/jdk/jdk11/linux-x86/bin:/home
/xayah/RevengeOS/prebuilts/jdk/jdk11/linux-x86/bin:/home/xayah/RevengeOS/out/soo
ng/host/linux-x86/bin:/home/xayah/RevengeOS/out/host/linux-x86/bin:/home/xayah/R
evengeOS/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9/bin:/home/xay
ah/RevengeOS/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/bin:/home/xay
ah/RevengeOS/development/scripts:/home/xayah/RevengeOS/prebuilts/devtools/tools:
/home/xayah/RevengeOS/external/selinux/prebuilts/bin:/home/xayah/RevengeOS/prebu
ilts/misc/linux-x86/dtc:/home/xayah/RevengeOS/prebuilts/misc/linux-x86/libufdt:/
home/xayah/RevengeOS/prebuilts/clang/host/linux-x86/llvm-binutils-stable:/home/x
ayah/RevengeOS/prebuilts/android-emulator/linux-x86_64:/home/xayah/RevengeOS/pre
builts/asuite/acloud/linux-x86:/home/xayah/RevengeOS/prebuilts/asuite/aidegen/li
nux-x86:/home/xayah/RevengeOS/prebuilts/asuite/atest/linux-x86:/home/xayah/.loca
l/bin:/home/xayah/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/b
in:/usr/games:/usr/local/games:/snap/bin make -j12 CFLAGS_MODULE="-fno-pic" -C  
O=/home/xayah/RevengeOS/out/soong/.temp/sbox334692632 ARCH=arm64 CROSS_COMPILE="
 aarch64-linux-android-" CROSS_COMPILE_ARM32="arm-linux-androideabi-"   headers_
install) failed with err "exit status 2"

[  0% 243/24451] Target product buildinfo: /home/xayah/RevengeOS/out/target/prod
Target product properties from: device/xiaomi/cas/product.prop
08:11:17 ninja failed with: exit status 1

#### failed to build some targets (01:24 (mm:ss)) ####

Here is the device tree: https://github.com/XayahSuSuSu/android_device_xiaomi_cas/tree/RevengeOS

**Comment by Fraaxius** [comment]
@XayahSuSuSu ?

**Comment by XayahSuSuSu** [comment]
> @XayahSuSuSu ?

Could you please give me some idea to fix it?

Must I use oss kernel?

**Comment by Fraaxius** [comment]
@XayahSuSuSu Yes
