### ISSUE TITLE
When to support

### ISSUE THREAD

**Issue by ghost** [RevengeOS/android_manifest#31]
powershare/Android.bp:16:1: "vendor.lineage.powershare@1.0-service.oneplus_kona" depends on undefined module "vendor.lineage.powershare@1.0"
error: sm8250-common/touch/Android.bp:16:1: "vendor.lineage.touch@1.0-service.oneplus_kona" depends on undefined module "vendor.lineage.touch@1

**Comment by Fraaxius** [comment]
@java67 You could try not to use that feature, it may be the solution.

Please, any questions in RevengeOS | Discussion o.O

**Comment by ArokzDP** [comment]
Thanks for your reply but how do you come to know my issue?

**Comment by ghost** [comment]
> @java67 You could try not to use that feature, it may be the solution.
> 
> Please, any questions in RevengeOS | Discussion o.O

Ok
