### ISSUE TITLE
I'm unable to build, any help?

### ISSUE THREAD

**Issue by coderastic** [RevengeOS/android_manifest#4]
`build/make/core/dex_preopt.mk:28: error: cannot assign to readonly variable: PRODUCT_SYSTEM_SERVER_CLASSPATH
22:20:14 ckati failed with: exit status 1

#### hidl-gen compilation failed, check above errors ####
`

**Comment by Chityanj** [comment]
Which device and trees? 
Also ask here 
https://t.me/itsrevengeos
